# Name:Harshavardhini K
# Roll No:235229108

## Exercise 1: Matrix Multiplication

### 1. Import NumPy Library:

In [1]:
import numpy as np

### 2. Define Matrices:

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

### 3. Perform Matrix Multiplication:

In [3]:
C = np.dot(A, B)

### 4. Print the Matrices and Result:

In [4]:
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Matrix C = A * B:")
print(C)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix C = A * B:
[[19 22]
 [43 50]]


## Exercise 2: Eigen Decomposition

### 1. Import NumPy Library:

In [5]:
import numpy as np

### 2. Define a Square Matrix:

In [6]:
A = np.array([[4, 2], [1, 3]])

### 3. Perform Eigen Decomposition:

In [7]:
eigenvalues, eigenvectors = np.linalg.eig(A)

### 4. Print the Matrix, Eigenvalues, and Eigenvectors:

In [8]:
print("Matrix A:")
print(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Matrix A:
[[4 2]
 [1 3]]
Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## Exercise 3: Singular Value Decomposition (SVD)

### 1. Import NumPy Library:

In [9]:
import numpy as np

### 2. Define a Matrix:

In [10]:
A = np.array([[3, 2, 2], [2, 3, -2]])

### 3. Perform SVD:

In [11]:
U, S, V = np.linalg.svd(A)

### 4. Print the Matrices and Singular Values:

In [12]:
print("Matrix A:")
print(A)
print("U matrix:")
print(U)
print("Singular values:")
print(S)
print("V matrix:")
print(V)

Matrix A:
[[ 3  2  2]
 [ 2  3 -2]]
U matrix:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular values:
[5. 3.]
V matrix:
[[-7.07106781e-01 -7.07106781e-01 -5.55111512e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


## Exercise 4: Determinant Calculation

### 1. Import NumPy Library:

In [13]:
import numpy as np

### 2. Define a Square Matrix:

In [14]:
A = np.array([[6, 1], [2, 3]])

### 3. Calculate the Determinant:

In [15]:
det = np.linalg.det(A)

### 4. Print the Matrix and Its Determinant:

In [16]:
print("Matrix A:")
print(A)
print("Determinant of A:")
print(det)

Matrix A:
[[6 1]
 [2 3]]
Determinant of A:
15.999999999999998


## Exercise 5: Norm Calculation

### 1. Import NumPy Library:

In [17]:
import numpy as np

### 2. Define a Vector:

In [18]:
v = np.array([3, 4])

### 3. Calculate L1 Norm:

In [19]:
L1_norm = np.linalg.norm(v, ord=1)

### 4. Calculate L2 Norm:

In [20]:
L2_norm = np.linalg.norm(v)

### 5. Print the Vector and Its Norms:

In [21]:
print("Vector v:")
print(v)
print("L1 norm of v:")
print(L1_norm)
print("L2 norm of v:")
print(L2_norm)

Vector v:
[3 4]
L1 norm of v:
7.0
L2 norm of v:
5.0
